apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5000"

  # Used in password-reset email links.
  # Local testing:
  FRONTEND_URL: "http://localhost:3000"

  # Later after Kubernetes frontend is running, replace with:
  # FRONTEND_URL: "http://<minikube-ip>:<frontend-nodeport>"