apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-demo-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus-demo
  namespaceSelector:
    any: true
  endpoints:
  - port: http
    path: /metrics
    interval: 15s